name: Essential Test

on:
  push:
    branches: [ "main", "dev-CI" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Run_unit_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check format
      run: rustup component list;
          cargo fmt -- --check

    - name: Build system
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
